AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for EventBridge RuleCloudTrail-Remediation
Resources:
  SsmAutomationCloudTrailRemediationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSM-Automation-CloudTrailRemediation
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: TrustEventBridgeService
            Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SSMCloudTrailRemediationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowStartAutomationExecution
                Effect: Allow
                Action: ssm:StartAutomationExecution
                Resource:
                  - !Sub arn:aws:ssm:us-east-1:${AWS::AccountId}:automation-definition/CloudTrail-StopLogging-Remediation:$DEFAULT
              - Sid: AllowPassRole
                Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/SSM-Automation-CloudTrailRemediation
              - Sid: CloudTrailControl
                Effect: Allow
                Action:
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:StartLogging
                Resource:
                  - !Sub arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/org-management-events
  CloudTrailRemediationDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Name: CloudTrail-StopLogging-Remediation
      Content:
        schemaVersion: "0.3"
        description: Auto-remediate CloudTrail logging when a specific trail is stopped
        assumeRole: "{{ AutomationAssumeRole }}"
        parameters:
          TrailName:
            type: String
            description: (Required) CloudTrail trail name or ARN
          AutomationAssumeRole:
            type: String
            description: (Optional) The ARN of the role that allows Automation to perform actions
            default: ""
        mainSteps:
          - name: GetCloudTrailStatus
            action: aws:assertAwsResourceProperty
            nextStep: End
            isCritical: false
            isEnd: false
            onFailure: step:AscertainStopped
            inputs:
              Service: cloudtrail
              Api: GetTrailStatus
              Name: "{{ TrailName }}"
              PropertySelector: $.IsLogging
              DesiredValues:
                - "True"
          - name: AscertainStopped
            action: aws:assertAwsResourceProperty
            nextStep: EnableLogging
            isCritical: false
            isEnd: false
            onFailure: step:End
            inputs:
              Service: cloudtrail
              Api: GetTrailStatus
              Name: "{{ TrailName }}"
              PropertySelector: $.IsLogging
              DesiredValues:
                - "False"
          - name: EnableLogging
            action: aws:executeAwsApi
            nextStep: WaitTurnedOn
            isEnd: false
            inputs:
              Service: cloudtrail
              Api: StartLogging
              Name: "{{ TrailName }}"
          - name: WaitTurnedOn
            action: aws:waitForAwsResourceProperty
            timeoutSeconds: 300
            isEnd: true
            inputs:
              Service: cloudtrail
              Api: GetTrailStatus
              Name: "{{ TrailName }}"
              PropertySelector: $.IsLogging
              DesiredValues:
                - "True"
          - name: End
            action: aws:sleep
            isEnd: true
            inputs:
              Duration: PT1S
  Rulea12bc15a:
    Type: AWS::Events::Rule
    Properties:
      Name: CloudTrail-Remediation
      EventPattern: >-
        {"detail-type":["AWS API Call via
        CloudTrail"],"detail":{"eventSource":["cloudtrail.amazonaws.com"],"eventName":["StopLogging"]},"source":["aws.cloudtrail"]}
      State: ENABLED
      Description: Regra para auto remediacão do StopLogging no trail da Org.
      EventBusName: default
      Targets:
        - Id: Idfb1b3e30-29ca-45ed-a1bd-82ee295ed7d8
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/CloudTrail-StopLogging-Remediation
          RoleArn:
            Fn::Sub: >-
              arn:${AWS::Partition}:iam::${AWS::AccountId}:role/SSM-Automation-CloudTrailRemediation
          Input: !Sub |
            {
              "AutomationAssumeRole": ["arn:aws:iam::${AWS::AccountId}:role/SSM-Automation-CloudTrailRemediation"],
              "TrailName": ["org-management-events"]
            }
Parameters: {}
